auth {
  pam {
    enabled=true
    module=hyprlock-startup
  }
  fingerprint {
    enabled=false
  }
}

background {
  monitor=
  color=rgb(11111b)
}

input-field {
  monitor=
  size=600, 100
  fade_on_empty=false
  fail_text=Authentication failed ($ATTEMPTS)
  font_color=rgb(cdd6f4)
  inner_color=rgb(1e1e2e)
  outer_color=rgb(89b4fa)
  outline_thickness=4
  placeholder_text=Enter account password
  position=0, 0
  rounding=0
  shadow_passes=0
  valign=center
  halign=center
}

label {
  monitor=
  color=rgb(cdd6f4)
  font_size=20
  position=0, -100
  text=Unlock the login keyring to start the desktop
  text_align=center
  valign=center
  halign=center
}
